### PR TITLE
update description template

### PR DESCRIPTION
**Pull request by pravi**
so it gives a hint that more work may be required to write a good description

### CODE REVIEW

**Comment by pravi** [comment]
@shanavas786 updated, please check

**Comment by shanavas786** [comment]
@pravi build fails with some error.

`dpkg-source --before-build node-is-arrayish-0.3.1
dpkg-source: error: syntax error in node-is-arrayish-0.3.1/debian/control at line 22: continued value line not in field
`

**Comment by pravi** [comment]
@shanavas786 its because there is an empty line in control before the extended description starts. I'm unable to find how this blank line got inserted can you help?

**Comment by pravi** [comment]
@shanavas786 fixed.

**Comment by shanavas786** [comment]
Looks good.
It would be more helpful if FIX_MEs in itp is also highlighted.
Just need to add path to itp file in `__init.py__ line 117`.

Would you like to handle this here or in another PR ?

**Comment by bignose-debian** [comment]
On 15-Feb-2017, shanavas wrote:
> Looks good.

I have commented on the proposed correction; I think it's only needed
because something was missed from the original; maybe a transcription
error.

Please see <URL:https://github.com/LeoIannacone/npm2deb/pull/51/commits/2ab4763f2209979d8842b6940913781ce27efccf#diff-58d9e529ecccead02d0ae54afe9d68f5L9>
for my comment describing what I think is a better fix (because it was
the original that I wrote :-)

-- 
 \          “Computer perspective on Moore's Law: Human effort becomes |
  `\           twice as expensive roughly every two years.” —anonymous |
_o__)                                                                  |
Ben Finney <ben@benfinney.id.au>

**Comment by pravi** [comment]
@shanavas786 fixed

**Comment by pravi** [comment]
@bignose-debian did not understand your last comment, since you are already active in github, a pr from you would be better than a patch in BTS as I have to play the extra role of a mediator :)

**Pull request merged**
