### PR TITLE
Bump dh and policy versions

### PR DESCRIPTION
**Pull request by avtobiff**
* Bump debhelper version: Lintian complains about old version.

    P: node-agent-base source: package-uses-old-debhelper-compat-version 10

* Bump standards-version to current (4.2.1).

### CODE REVIEW

**Comment by avtobiff** [comment]
I don't se any need to keep `STANDARDS_VERSION` if latest is fetched.

**Comment by avtobiff** [comment]
Do you want me to remove the `STANDARDS_VERSION` change from the pull request?

**Comment by shanavas786** [comment]
> Do you want me to remove the `STANDARDS_VERSION` change from the pull request?

Yes please

**Comment by shanavas786** [comment]
closing as #132 is merged

**Pull request closed without merging**
