### PR TITLE
bump Standards-Version to 4.0.0

### PR DESCRIPTION
**Pull request by shanavas786**
Discussion in Debian bug tracker
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867298

### CODE REVIEW

**Comment by pravi** [comment]
Bump to 4.1.0

**Comment by shanavas786** [comment]
Thanks, Done

**Comment by pravi** [comment]
4.1.1 is out.

**Comment by shanavas786** [comment]
#92 is merged. This can be closed now.

**Pull request closed without merging**
