### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by guimard**
Hi,

some improvements:
 * update S-V
 * use pkg-js-tools for tests/autopkgtest
 * optimize debian/watch

### CODE REVIEW

**Comment by guimard** [comment]
Hello @LeoIannacone, do you want co-maint on this software ? I'm not able to write many things in Python but I can help.

Cheers, Xavier

**Comment by LeoIannacone** [comment]
@guimard welcome onboard! :)

**Comment by guimard** [comment]
@LeoIannacone: thanks for invitation, but I've no write access after accepting it. Did I miss something ?

**Comment by LeoIannacone** [comment]
The PRs must always been approved by somebody else

**Comment by LeoIannacone** [comment]
Try now

**Comment by guimard** [comment]
OK, thanks

**Pull request merged**
