### PR TITLE
Avoid searching on anonscm(Fixes #106)

### LINKED ISSUE #106: npm2deb search graceful-fs giving error
I am running this command  on docker image of  debian:sid 

```

root@f2e7e0e7914d:/# npm2deb search graceful-fs

Looking for similar package:
  node-graceful-fs (4.1.11-1) (unstable)

Looking for existing repositories:
Traceback (most recent call last):
  File "/usr/bin/npm2deb", line 7, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/npm2deb/scripts.py", line 138, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/npm2deb/scripts.py", line 156, in search_for_module
    _helper.search_for_repository(node_module)
  File "/usr/lib/python3/dist-packages/npm2deb/helper.py", line 35, in search_for_repository
    (url_base, repo, module)).read()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

### PR DESCRIPTION
**Pull request by divatemangesh**
Since, alioth is recently shut down, We should stop searching on anonscm

### CODE REVIEW

**Comment by shanavas786** [comment]
You can remove lines 41, 42 and 27 also

**Comment by pravi** [comment]
@shanavas786 I think we should also search in https://alioth-archive.debian.org/git/pkg-javascript/ and https://alioth-archive.debian.org/git/collab-maint/ as some packages may not be migrated to salsa. This can be done only as a fallback case in case the module is not found in salsa.

**Comment by shanavas786** [comment]
yes, but alioth-archive doesn't provide search functionality as alioth did.
Either we have to search name in the body of above pages or use HEAD request to check if the file exists there.
I was checking if alioth-archive supports HEAD request but the server seems to be very slow.

**Comment by pravi** [comment]
@shanavas786 I think we can just cache two pages (pkg-javascript and collab-maint) and do a local regex search. They will not be changing again.

**Comment by pravi** [comment]
Or even embed the list inside npm2deb

**Comment by pravi** [comment]
if we embed, we can remove the packages already on salsa.

**Comment by shanavas786** [comment]
we use https://wiki.debian.org/Javascript/Nodejs/Database for similar purpose.
I think its better we create another page for packages not ported to salsa.

**Comment by pravi** [comment]
But that is for a dynamic data, here this data will never change. I don't see any benefit to making it dynamic.

**Comment by pravi** [comment]
Or rather, it will only reduce and become zero when all repos are migrated.

**Comment by pravi** [comment]
Your call, I'm fine with creating a wiki page as well.

**Pull request merged**
