### PR TITLE
Fix failure when creating @types/<name> modules

### LINKED ISSUE #94: npm2deb create @types/jquery fails
Even when npm is updated to latest (npm install -g npm), npm2deb fails.

```
praveen@mahishasura:~/forge$ npm2deb view @types/jquery
Name:                                   @types/jquery
Version:                                3.2.16
Description:                            None
Homepage:                               https://npmjs.com/package/@types/jquery
License:                                Expat
Debian:                                 None (None)
praveen@mahishasura:~/forge$ npm2deb create @types/jquery
Error: directory @types/jquery already exists.
praveen@mahishasura:~/forge$ npm --version
5.5.1
```

### PR DESCRIPTION
**Pull request by shanavas786**
Fixes #94

### CODE REVIEW

**Comment by pravi** [comment]
@shanavas786 looks good to me. Though fakeupstream will need to be updated to get the tarballs.

  http://qa.debian.org/cgi-bin/fakeupstream.cgi?upstream=npmjs/@types/jquery failed: 500 Internal Server Error
uscan info: Scan finished

**Comment by pravi** [comment]
Opened https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900872

**Comment by pravi** [comment]
@shanavas786 fakeupstream service is fixed but watch file needs fixing (file name to match is jquery and not @types/jquery).

`http://qa.debian.org/cgi-bin/fakeupstream.cgi?upstream=npmjs/@types/jquery .*=jquery-(\d.*)\.(?:tgz|tar\.(?:gz|bz2|xz))
`

**Comment by pravi** [comment]
This is fixed in #109 and can be closed.

**Comment by shanavas786** [comment]
In favor of #109

**Pull request closed without merging**
